#!/usr/bin/env bash
BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RED='\E[1;31m'
RESET='\E[0m'

# Check if root
if [ "$(id -u)" != "0" ]; then
   echo -e "${RED}This script must be run as root${RESET}" 1>&2
   exit 1
fi

# Get cuda version
CUDA_VERSION=$(nvcc --version | grep release | awk '{print $6}' | awk -F, '{print $1}')

# Test if cuda is installed
if [ -n "${CUDA_VERSION}" ]; then
    echo -e "${GREEN}❯❯❯ CUDA ${RED}${CUDA_VERSION}${CYAN} is installed${RESET}"
else
    echo -e "${RED}❯❯❯ CUDA is not installed!!! Aborting...${RESET}"
    exit 1
fi


echo -e "${BLUE}❯❯❯ ${CYAN}Installing prerequisites for GPU openALPR local binary${RESET}"
# this includes all the ones missing from OpenALPR's guide.
apt install libtesseract-dev git cmake build-essential libleptonica-dev -y
apt install liblog4cplus-dev libcurl3-dev libcurl4-openssl-dev -y
apt install beanstalkd -y
#sudo apt install openjdk-8-jdk -y

echo -e "${BLUE}❯❯❯ ${CYAN}Installing OpenALPR${RESET}"
mkdir -p /tmp/openalpr-build
# Clone the latest code from GitHub
git clone https://github.com/openalpr/openalpr.git /tmp/openalpr-build

# Set up the build directory
cd /tmp/openalpr-build/src || return
mkdir build
cd build  || return

# Set up the compile environment
# build with python bindings
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc –DCOMPILE_GPU=1 -D WITH_GPU_DETECTOR=ON ..

# Compile the library
make -j"$(nproc)"

# Install the binaries/libraries to your local system (prefix is /usr)
make install

echo -e "${BLUE}❯❯❯ ${CYAN}Testing OpenALPR${RESET}"
# Test the library
wget http://plates.openalpr.com/h786poj.jpg -O lp.jpg
alpr lp.jpg
rm lp.jpg

echo -e "${BLUE}❯❯❯ ${CYAN}Installed OpenALPR,${RED} DON'T FORGET TO ENABLE GPU IN ${GREEN}/etc/openalpr/<x>.conf${RESET}"
