DEF_SRV_SYS_CONFDIR: str = "/opt/zm_ml/etc/zm_ml"
DEF_SRV_SYS_DATADIR: str = "/opt/zm_ml/var/lib/zm_ml"
DEF_SRV_SYS_TMPDIR: str = "/opt/zm_ml/var/tmp/zm_ml"
DEF_SRV_SYS_IMAGEDIR: str = "/opt/zm_ml/var/lib/zm_ml/images"
DEF_SRV_SYS_MODELDIR: str = "/opt/zm_ml/var/lib/zm_ml/models"
DEF_SRV_SYS_THREAD_WORKERS: int = 4
DEF_SRV_LOGGING_LEVEL: int = 20
DEF_SRV_LOGGING_CONSOLE_ENABLED: bool = True
DEF_SRV_LOGGING_SYSLOG_ENABLED: bool = False
DEF_SRV_LOGGING_FILE_ENABLED = True
DEF_SRV_LOGGING_FILE_PATH: str = "/opt/zm_ml/var/log/zm"
DEF_SRV_LOGGING_FILE_FILENAME_PREFIX: str = "zmml"
