#!/usr/bin/env bash

# This will attempt to set up the environment and install ZoneMinder Machine Learning library using git
TESTING=${TESTING:-false}
GIT=${GIT:-$(which git)}
PIP=${PIP:-pip3}
PYTHON=${PYTHON:-python3}
INSTALLER=${INSTALLER:-}

# utility functions for color coded pretty printing
print_error() {
    COLOR="\033[1;31m"
    NOCOLOR="\033[0m"
    echo -e "${COLOR}ERROR::${NOCOLOR} $1"
}

print_important() {
    COLOR="\033[0;34m"
    NOCOLOR="\033[0m"
    echo -e "${COLOR}IMPORTANT::${NOCOLOR} $1"
}

print_warning() {
    COLOR="\033[0;33m"
    NOCOLOR="\033[0m"
    echo -e "${COLOR}WARNING::${NOCOLOR} $1"
}

print_success() {
    COLOR="\033[1;32m"
    NOCOLOR="\033[0m"
    echo -e "${COLOR}Success::${NOCOLOR} $1"
}

get_distro() {
    local DISTRO=''
    DISTRO=$( (lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1)
    local DISTRO_NORM='ubuntu'
    if echo "${DISTRO}" | grep -iqF 'ubuntu'; then
        DISTRO_NORM='debian'
    elif echo "${DISTRO}" | grep -iqF 'centos'; then
        DISTRO_NORM='centos'
    elif echo "${DISTRO}" | grep -iqF 'debian'; then
        DISTRO_NORM='debian'
    elif echo "${DISTRO}" | grep -iqF 'raspbian'; then
        DISTRO_NORM='debian'
    elif echo "${DISTRO}" | grep -iqF 'fedora'; then
        DISTRO_NORM='fedora'
    elif echo "${DISTRO}" | grep -iqF 'opensuse'; then
        DISTRO_NORM='opensuse'
    elif echo "${DISTRO}" | grep -iqF 'arch'; then
        DISTRO_NORM='arch'
    elif echo "${DISTRO}" | grep -iqF 'alpine'; then
        DISTRO_NORM='alpine'
    fi
    echo ${DISTRO_NORM}
}

get_installer() {
    local DISTRO=''
    DISTRO=$(get_distro)
    local installer='apt-get install -qqy'
    case $DISTRO in
        debian)
            installer='apt-get install -qqy'
            ;;
        centos)
            installer='yum install -y'
            ;;
        arch)
            installer='pacman -S --noconfirm'
            ;;
        fedora)
            installer='dnf install -y'
            ;;
        alpine)
            installer='apk add --quiet'
            ;;
        opensuse)
            installer='zypper install -y'
            ;;
    esac
    echo "${installer}"
}





# NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this
# separately; see below.
TEMP=$(getopt -o thg:p:u:i: --long testing,help,git:,pip:,python:,installer: \
              -n 'bootstrap' -- "$@")
if [ $? != 0 ] ; then print_error "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around '$TEMP': they are essential!
eval set -- "$TEMP"

while true; do
  case "$1" in
    -t | --testing ) TESTING=true; shift ;;
    -h | --help ) usage ;;
    -g | --git ) GIT="$2"; shift 2 ;;
    -p | --pip ) PIP="$2"; shift 2 ;;
    -u | --python ) PYTHON="$2"; shift 2 ;;
    -i | --installer ) INSTALLER="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done




usage() {
    echo "Usage: bootstrap [-t|--testing] [-h|--help] [-g|--git GIT_BINARY] [-p|--pip PIP_BINARY] [-u|--python PYTHON_BINARY] [-i|--installer INSTALLER_COMMAND]"
    echo
    echo "Optional:"
    echo "  -t, --testing:      Enable testing mode"
    echo "  -g, --git:          Path to git executable"
    echo "  -p, --pip:          Path to pip executable"
    echo "  -u, --python:       Path to python3 executable"
    echo "  -i, --installer:    Path to installer executable with args and flags"
    echo "  -h, --help:         Print this help message"
    exit 1
}

print_important "This script will attempt to bootstrap the installation of ZoneMinder Machine Learning (ZM_ML) library."
if [[ -z "${INSTALLER}" ]]; then
  echo "Attempting to determine package manager install command"
    INSTALLER=$(get_installer)
fi
echo "Distro Based On: $(get_distro) -- Install Command: ${INSTALLER}"
echo
    echo "Checking for git binary...."
    if [ -z "$GIT" ]; then
        print_error "git not found, installing git..."
        if [[ "$TESTING" == "true" ]]; then
            echo "TESTING: $INSTALLER git"
        else
            "sudo -H ${INSTALLER} git"
        fi
    fi
    echo "Checking for pip3 binary...."
    if [ -z "$PIP" ]; then
        print_error "pip3 not found, installing pip3..."
        if [[ "$TESTING" == "true" ]]; then
            print_important "TESTING: $INSTALLER python3-pip"
        else
            "sudo -H ${INSTALLER} python3-pip"
        fi

    fi
    echo "Checking for python3 binary...."
    if [ -z "$PYTHON" ]; then
        print_error "python3 not found, installing python3..."
        if [[ "$TESTING" == "true" ]]; then
            print_important "TESTING: $INSTALLER python3"
        else
            "sudo -H ${INSTALLER} python3"
        fi
    fi
    deps=('requests' 'psutil')
    for dep in "${deps[@]}"; do
        echo "Checking for ${dep} python3 module...."
        if ! python3 -c "import ${dep}" 2>/dev/null; then
            print_error "${dep} python3 module not found, installing ${dep} python3 module..."
            if [[ "$TESTING" == "true" ]]; then
                print_important "TESTING: $PIP install ${dep}"
            else
                "sudo -H ${PIP} install ${dep}"
            fi
          else
            print_success "${dep} python3 module found"
        fi
    done
    echo
    echo "Cloning ZM_ML library..."
    if [[ "$TESTING" == "true" ]]; then
      print_important "TESTING: $GIT clone https://github.com/baudneo/ZM_ML"
    else
      "${GIT} clone https://github.com/baudneo/ZM_ML"
      cd ZM_ML || exit 1
    fi
    if [[ "$TESTING" == "true" ]]; then
      print_important "TESTING: ${PYTHON} ./examples/install.py"
    else
      print_important "Installing ZM_ML using ./examples/install.py..."
      "${PYTHON}" ./examples/install.py # >/dev/null 2>&1

    fi
    echo
