client:
#  THESE_WILL_BE_IMPORTED: "to the config file to be used as variables"
#  STORE: "sensitive data in this file"
  #######################################################################
  ZM_API: ${ML_INSTALL_CLIENT_ZM_API}
  ZM_PORTAL: ${ML_INSTALL_CLIENT_ZM_PORTAL}
  ZM_USER: ${ML_INSTALL_CLIENT_ZM_USER}
  ZM_PASS: ${ML_INSTALL_CLIENT_ZM_PASS}

  GOTI_HOST:
  GOTI_PORTAL:
  GOTI_TOKEN:

  PUSHOVER_TOKEN: <change me>
  PUSHOVER_KEY: <change me>

  LINKURL_USER:
  LINKURL_PASS:

  MQTT_BROKER: 127.0.0.1
  MQTT_USERNAME:
  MQTT_PASSWORD:

server:
  # Store server secrets here
#  THESE_WILL_BE_IMPORTED: "to the config file to be used as variables"
#  STORE: "sensitive data in this file"
  #######################################################################
  JWT_SIGN_PHRASE: 'WIP, change me once this is implemented'
